# ---- Base image ----
FROM python:3.12-slim

# Install nginx
RUN apt-get update && \
    apt-get install -y curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy entire project FIRST (because of -e .)
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8080

RUN python n2t -c dev-config-docker.env loaddb

ENV N2T_SETTINGS=/app/dev-config-docker.env

CMD ["gunicorn", "n2t.app:app", "-k", "uvicorn.workers.UvicornWorker", "--workers", "3", "--bind", "0.0.0.0:8000"]