[tool.poetry]
name = "n2t"
version = "0.7.2"
description = "Implementation of N2T in python"
authors = ["datadavev <605409+datadavev@users.noreply.github.com>"]
license = "MIT"

[tool.poetry_bumpversion.file."n2t/__init__.py"]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6"
fastapi = "^0"
pydantic-settings = "^2"
rslv = {git = "https://github.com/CDLUC3/resolver.git", branch="develop"}
click = "^8.1.7"

[tool.poetry.dev-dependencies]
pytest = "^7"
uvicorn = "^0"

[tool.poetry.scripts]
n2t = 'n2t.__main__:main'

[tool.poetry.group.dev.dependencies]
uvicorn = "^0.27.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
