[tool.poetry]
name = "n2t"
version = "0.9.1"
description = "Implementation of N2T in python"
authors = ["datadavev <605409+datadavev@users.noreply.github.com>"]
license = "MIT"

[tool.poetry_bumpversion.file."n2t/__init__.py"]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6"
fastapi = "^0"
pydantic-settings = "^2"
rslv = {git = "https://github.com/CDLUC3/resolver.git", branch="main"}
click = "^8.1.7"
httpx = "^0.27.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.29"}
aiosqlite = "^0.20.0"

[tool.poetry.dev-dependencies]
pytest = "^7"
uvicorn = "^0"

[tool.poetry.scripts]
n2t = 'n2t.__main__:main'

[tool.poetry.group.dev.dependencies]
uvicorn = "^0.27.1"
geoip2 = "^4.8.0"
textual = "^0.56.4"
hopper = {git = "https://github.com/datadavev/looseroo.git"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
