[tool.poetry]
name = "n2t"
version = "0.1.5"
description = "Implementation of N2T in python"
authors = ["datadavev <605409+datadavev@users.noreply.github.com>"]
license = "MIT"
packages = [
	{ include = "lib_n2t", from="micron2t" },
	{ include = "scripts" }
]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8"
PyYAML = "^6"
click-logging = "^1"
pyldapi = "^4"
fastapi = "^0"
orjson = "^3"
lmdbm = "^0"
pydantic-settings = "^2.0.3"

[tool.poetry.dev-dependencies]
ipykernel = "^6"
pytest = "^7"

[tool.poetry.scripts]
n2t = 'scripts.n2t_cli:main'

[tool.poetry.group.dev.dependencies]
uvicorn = "^0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
