user: "{{ lookup('env', 'USER') | default('ezid') }}"
group: "{{ user }}"
app_dir: "{{ lookup('env', 'HOME') | default('/ezid') }}"
deploy_dir: "{{ app_dir }}/n2t"
python_home: "{{ deploy_dir }}/venv/"
 
n2t_repo: 'https://github.com/CDLUC3/n2t.git'
n2t_version: 'main'
