---
title: Scheme Handling
---

The identifier `scheme` is the first portion of an identifier, delimited by the appearance of the first colon (":") character in an identifier string.

The identifier scheme indicates the type of identifier, which in turn indicates how the identifier should be further handled in the resolution process.

Schemes in N2T are imported from the legacy information available from the original N2T implementation through the YAML file that may be retrieved from `https://n2t.net/e/n2t_full_prefixes.yaml`.

The YAML source defines several "types" of entry: `scheme`, `shoulder`, `naan`, `synonym`, and `commonspfx`. For the N2T scheme resolver, the `shoulder` and `naan` entries are ignored as those are handled by downstream identifier prefix or value resolvers.

The `synonym` type provides an alternative scheme name for another `scheme` or `commonspfx` entry.

The `commonspfx` entries include minimal information for a scheme with just a redirect target provided.

The core model of a scheme record is very simple:

